name: Trigger auto deployment for wauwatosa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/wauwatosa-AutoDeployTrigger-4771865b-188c-4883-8e93-e3cbbf6f1e00.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WAUWATOSA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WAUWATOSA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WAUWATOSA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: eddoazurecontainers.azurecr.io
          registryUsername: ${{ secrets.WAUWATOSA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WAUWATOSA_REGISTRY_PASSWORD }}
          containerAppName: wauwatosa
          resourceGroup: eddo-container-apps
          imageToBuild: eddoazurecontainers.azurecr.io/wauwatosa:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


